### ISSUE TITLE
GTFS-RT support

### ISSUE THREAD

**Issue by mpaine-act** [alen-smajic/3D-Public-Transport-Simulator#1]
Has there been any work yet related to adding GTFS-RT vehicle positions to the software?  It would be interesting to use this along with Open Trip Planner for mobile devices.

**Comment by alen-smajic** [comment]
Hi @mpaine-act,
unfortunately no. The application currently supports only OpenStreetMap and Mapbox data. As soon as I get some free time I will look into adding this or if you are interested feel free to implement it. The project is open-source :)

**Comment by mpaine-act** [comment]
Good point :)  I'm working on a trip planner and having a "street view" would be interesting.
