### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by if7D0** [alen-smajic/3D-Public-Transport-Simulator#3]
Hello, I'm from Indonesia :) I think your project is really amazing, WOW🤩
Can you help me to run the program on my computer (but not the .exe file)?
Is the video tutorial available? Thank you :)

**Comment by alen-smajic** [comment]
Hello,

thank you for your kind words.
It has been quite some time that I worked on this project, but from my memory it should be enough to open the folder "Public Transport Simulator - Unity Project" from this repo within the Unity game engine. That should load all the files and get you in the development stage. 
Hope that helps :)
